mod parser;
mod lex;


// FIXME: this is generated by the stupid Copilot, and therefore I must rewrite it
fn substitute(expr: parser::Expression, param: &str, arg: parser::Expression) -> parser::Expression {
    match expr {
        parser::Expression::Variable(name) => {
            if name == param {
                arg
            } else {
                parser::Expression::Variable(name)
            }
        }
        parser::Expression::Function { param: inner_param, body } => {
            if inner_param == param {
                parser::Expression::Function { param: inner_param, body }
            } else {
                let body = substitute(*body, param, arg);
                parser::Expression::Function { param: inner_param, body: Box::new(body) }
            }
        }
        parser::Expression::Application { function, arg: inner_arg } => {
            let function = substitute(*function, param, arg.clone());
            let inner_arg = substitute(*inner_arg, param, arg);
            parser::Expression::Application { function: Box::new(function), arg: Box::new(inner_arg) }
        }
    }
}

// FIXME: this is generated by the stupid Copilot, and therefore I must rewrite it
fn simplefy(expr: parser::Expression) -> parser::Expression {
    match expr {
        parser::Expression::Application { function, arg } => {
            let function = simplefy(*function);
            let arg = simplefy(*arg);
            match function {
                parser::Expression::Function { param, body } => {
                    let body = *body;
                    let body = substitute(body, &param, arg);
                    simplefy(body)
                }
                _ => parser::Expression::Application {
                    function: Box::new(function),
                    arg: Box::new(arg),
                },
            }
        }
        parser::Expression::Function { param, body } => {
            let body = simplefy(*body);
            parser::Expression::Function {
                param,
                body: Box::new(body),
            }
        }
        parser::Expression::Variable(_) => expr,
    }
}

fn main() {
    println!("Hello, world!");
    let s = lex::TokenStream::new(std::io::stdin());
    let mut parser = parser::Parser::new(s);

    loop {
        match parser.parse() {
            Ok(root) => {
                println!("Parsed expression: {}", root);
                let root = simplefy(root);
                println!("Simplified expression: {}", root);
            },
            Err(e) => eprintln!("Error parsing expression: {}", e),
        }
    }

    // while let Some(token) = s.next() {
    //     println!("{:?}", token);
    // }
}
