use std::{
    collections::HashMap,
    io::{Read, Write},
};

use crate::{lex::Token, parser::Expression};

mod lex;
mod parser;

// FIXME: this is generated by the stupid Copilot, and therefore I must rewrite it
fn substitute(
    expr: parser::Expression,
    param: &str,
    arg: parser::Expression,
) -> parser::Expression {
    match expr {
        parser::Expression::Variable(name) => {
            if name == param {
                arg
            } else {
                parser::Expression::Variable(name)
            }
        }
        parser::Expression::Function {
            param: inner_param,
            body,
        } => {
            if inner_param == param {
                parser::Expression::Function {
                    param: inner_param,
                    body,
                }
            } else {
                let body = substitute(*body, param, arg);
                parser::Expression::Function {
                    param: inner_param,
                    body: Box::new(body),
                }
            }
        }
        parser::Expression::Application {
            function,
            arg: inner_arg,
        } => {
            let function = substitute(*function, param, arg.clone());
            let inner_arg = substitute(*inner_arg, param, arg);
            parser::Expression::Application {
                function: Box::new(function),
                arg: Box::new(inner_arg),
            }
        }
    }
}

// FIXME: this is generated by the stupid Copilot, and therefore I must rewrite it
fn simplefy(expr: parser::Expression) -> parser::Expression {
    match expr {
        parser::Expression::Application { function, arg } => {
            let function = simplefy(*function);
            let arg = simplefy(*arg);
            match function {
                parser::Expression::Function { param, body } => {
                    let body = *body;
                    let body = substitute(body, &param, arg);
                    simplefy(body)
                }
                _ => parser::Expression::Application {
                    function: Box::new(function),
                    arg: Box::new(arg),
                },
            }
        }
        parser::Expression::Function { param, body } => {
            let body = simplefy(*body);
            parser::Expression::Function {
                param,
                body: Box::new(body),
            }
        }
        parser::Expression::Variable(_) => expr,
    }
}

fn help() {
    println!(
        "This is a simple lambda calculus interpreter.

eval or e <expression>            evaluate an expression
 set or s <variable> <expression> define a variable
 cat or c <variable>              look at its value
        help                      show this message
        exit                      exit the interpreter"
    );
}

fn main() {
    println!(
        "No copyright (CC0) 2026 Youzhe Zhen
type `help` for helps, `exit` to exit"
    );
    let mut variables = HashMap::<String, Expression>::new();

    loop {
        print!("<3 "); // heart LOL
        std::io::stdout().flush().unwrap();
        let mut s = lex::TokenStream::new(std::io::stdin());
        let Some(Token::Identifyer(command)) = s.next() else {
            continue;
        };
        match command.as_str() {
            "exit" => break,
            "help" => {
                help();
                continue;
            }
            "eval" | "e" => {
                let mut parser = parser::Parser::new(s);
                match parser.parse() {
                    Ok(expr) => {
                        println!("Parsed expression: {}", expr);
                        let expr = simplefy(expr);
                        println!("Simplified expression: {}", expr);
                    }
                    Err(e) => {
                        eprintln!("Error parsing expression: {}", e);
                        /* Skip the rest of the line, so that we can read the next expression
                        FIXME: sometimes it needs to re-press the enter key */
                        std::io::stdin().read_line(&mut String::new()).unwrap();
                    }
                };
            }
            "set" | "s" => {
                let Some(Token::Identifyer(name)) = s.next() else {
                    eprintln!("set: Expected variable name");
                    continue;
                };
                let mut parser = parser::Parser::new(s);
                match parser.parse() {
                    Ok(expr) => {
                        let expr = simplefy(expr);
                        println!("{} = {}", name, expr);
                        variables.insert(name, expr);
                    }
                    Err(e) => {
                        eprintln!("Error parsing expression: {}", e);
                        /* Skip the rest of the line, so that we can read the next expression
                        FIXME: sometimes it needs to re-press the enter key */
                        std::io::stdin().read_line(&mut String::new()).unwrap();
                    }
                };
            }
            "cat" | "c" => {
                let Some(Token::Identifyer(name)) = s.next() else {
                    eprintln!("cat: Expected variable name");
                    continue;
                };
                if let Some(expr) = variables.get(&name) {
                    println!("{} = {}", name, expr)
                } else {
                    println!("{} =", name);
                }
            }
            _ => {
                eprintln!("Unknown command: {}", command);
                continue;
            }
        }
    }
}
