use std::{collections::HashMap, io::Write};

use crate::{lex::Token, parser::Expression};

mod lex;
mod parser;

// FIXME: this is generated by the stupid Copilot, and therefore I must rewrite it
fn substitute(
    expr: parser::Expression,
    param: &str,
    arg: parser::Expression,
) -> parser::Expression {
    match expr {
        parser::Expression::Variable(name) => {
            if name == param {
                arg
            } else {
                parser::Expression::Variable(name)
            }
        }
        parser::Expression::Function {
            param: inner_param,
            body,
        } => {
            if inner_param == param {
                parser::Expression::Function {
                    param: inner_param,
                    body,
                }
            } else {
                let body = substitute(*body, param, arg);
                parser::Expression::Function {
                    param: inner_param,
                    body: Box::new(body),
                }
            }
        }
        parser::Expression::Application {
            function,
            arg: inner_arg,
        } => {
            let function = substitute(*function, param, arg.clone());
            let inner_arg = substitute(*inner_arg, param, arg);
            parser::Expression::Application {
                function: Box::new(function),
                arg: Box::new(inner_arg),
            }
        }
    }
}

// FIXME: this is generated by the stupid Copilot, and therefore I must rewrite it
fn simplefy(expr: parser::Expression) -> parser::Expression {
    match expr {
        parser::Expression::Application { function, arg } => {
            let function = simplefy(*function);
            let arg = simplefy(*arg);
            match function {
                parser::Expression::Function { param, body } => {
                    let body = *body;
                    let body = substitute(body, &param, arg);
                    simplefy(body)
                }
                _ => parser::Expression::Application {
                    function: Box::new(function),
                    arg: Box::new(arg),
                },
            }
        }
        parser::Expression::Function { param, body } => {
            let body = simplefy(*body);
            parser::Expression::Function {
                param,
                body: Box::new(body),
            }
        }
        parser::Expression::Variable(_) => expr,
    }
}

fn help() {
    println!(
        "This is a simple lambda calculus interpreter.

eval or e <expression>            evaluate an expression
 set or s <variable> <expression> define a variable
 cat or c <variable>              look at its value
        help                      show this message
        exit                      exit the interpreter"
    );
}

fn get_expression(stream: &mut lex::TokenStream) -> Option<parser::Expression> {
    let tokens = stream.collect();
    let parser = parser::Parser::new(tokens);
    match parser.parse() {
        Ok(expr) => Some(expr),
        Err(e) => {
            eprintln!("Error parsing expression: {}", e);
            None
        }
    }
}

fn main() {
    println!(
        "No copyright (CC0) 2026 Youzhe Zhen
type `help` for helps, `exit` to exit"
    );
    let mut variables = HashMap::<String, Expression>::new();

    loop {
        print!("<3 "); // heart LOL
        std::io::stdout().flush().unwrap();

        let mut str = String::new();
        std::io::stdin().read_line(&mut str).unwrap();
        let mut stream = lex::TokenStream::new(str.chars());

        let Some(Token::Identifyer(command)) = stream.next() else {
            /* lines begin with anything but identifyer is a comment */
            continue;
        };
        match command.as_str() {
            "exit" => break,
            "help" => {
                help();
                continue;
            }
            "eval" | "e" => {
                let Some(expr) = get_expression(&mut stream) else {
                    continue;
                };
                println!("{}", simplefy(expr));
            }
            "set" | "s" => {
                let Some(Token::Identifyer(name)) = stream.next() else {
                    eprintln!("set: Expected variable name");
                    continue;
                };
                let Some(expr) = get_expression(&mut stream) else {
                    continue;
                };
                println!("{} = {}", name, expr);
                variables.insert(name, expr);
            }
            "cat" | "c" => {
                let Some(Token::Identifyer(name)) = stream.next() else {
                    eprintln!("cat: Expected variable name");
                    continue;
                };
                if let Some(expr) = variables.get(&name) {
                    println!("{} = {}", name, expr)
                } else {
                    println!("{} =", name);
                }
            }
            _ => {
                eprintln!("Unknown command: {}", command);
                continue;
            }
        }
    }
}
